
services:

  webserver:
    image: nginx:alpine
    container_name: ${APP}-webserver
    working_dir: /mnt/api
    volumes:
      - ./api:/mnt/api
      - ./app:/mnt/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
      - "8081:8081"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: ${APP}-php-fpm
    working_dir: /mnt/api/
    volumes:
      - ./api:/mnt/api/
      - .env:/mnt/api/.env
      - ./docker/php-fpm/php-ini-overrides.local.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
    ports:
      - "8000:8000"
      - "8002:8002"

  database:
    image: mysql:8.0.32
    container_name: ${APP}-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./data/volumes/mysql:/var/lib/mysql
